name: Build the CI job for nodejs application
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ./nodejs-app-nov-2025

      - name: Run tests
        run: npm test
        working-directory: ./nodejs-app-nov-2025

      - name: list all the files and folder in build directory
        run: ls
        working-directory: ./nodejs-app-nov-2025

      - name: Echo username and password
        env:
          USERNAME: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}   
        run: |
          echo "Username length: ${#USERNAME}"
          echo "Password length: ${#PASSWORD}"
          echo "Username is set: $([[ -n "$USERNAME" ]] && echo 'YES' || echo 'NO')"
          echo "Password is set: $([[ -n "$PASSWORD" ]] && echo 'YES' || echo 'NO')"
       

      - name: Upload artifacts check the node js application path 
        uses: actions/upload-artifact@v4
        with:
          name: nodejs-app-artifacts
          path: ./nodejs-app-nov-2025